openapi: 3.0.0
info:
  title: Account-Relationship
  version: '1.0'
  description: Ship to interface CPQ
  contact:
    name: bharath M
    url: 'http://se.com'
    email: bharath.m@se.com
servers:
  - url: 'https://api.qa.se.com/v1/customer-order/back-office/accountrelationship'
paths:
  /relationship:
    post:
      description: shipto get interface
      summary: Your POST endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    operatingUnit:
                      type: string
                    accountNumber:
                      type: string
                    customerName:
                      type: string
                    custAcctSiteId:
                      type: string
                    address1:
                      type: string
                    address2:
                      type: string
                    address3:
                      type: string
                    address4:
                      type: string
                    city:
                      type: string
                    stateProvince:
                      type: string
                    county:
                      type: string
                    country:
                      type: string
                    postalCode:
                      type: string
                    status:
                      type: string
                    location:
                      type: string
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
      operationId: Post-AccountRelationship
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                accountNumber:
                  type: string
                  description: Account number
                operatingUnit:
                  type: string
                  description: operation unit
                address1:
                  type: string
                  description: address line one
                address2:
                  type: string
                  description: address line 2
                address3:
                  type: string
                  description: address line 3
                address4:
                  type: string
                  description: address line 4
                city:
                  type: string
                  description: city
                stateProvince:
                  type: string
                  description: provincial state
                county:
                  type: string
                  description: county
                zipCode:
                  type: string
                  description: zip code
                country:
                  type: string
                  description: country
                relationShip:
                  type: string
                  description: relation ship
                location:
                  type: string
            examples:
              Relationship example -1:
                value:
                  accountNumber: '11952'
                  operatingUnit: APCC OU
                  address1: 'DAI 3MD TECHNOLOGIES,INC'
                  address2: 17735 NE 65th ST STE 130
                  address3: ''
                  address4: ''
                  city: ''
                  stateProvince: ''
                  county: ''
                  zipCode: ''
                  country: ''
                  relationShip: ''
                  location: ''
        description: ''
      parameters: []
    parameters: []
components:
  schemas: {}
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://api.qa.se.com/token'
          refreshUrl: ''
          scopes: {}
security:
  - oauth2: []