openapi: 3.0.0
info:
  title: Reffed Dog Test
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/dog/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      $ref: 'http://chelsea.stoplight-local.com:8080/api/v1/projects/chelsea/create-non-empty/nodes/reference/dog.yaml'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  tagId:
                    type: string
components:
  schemas: {}
