openapi: 3.0.0
info:
  title: Test API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/dog/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Get A Dog
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
      parameters:
        - $ref: 'http://chelsea.stoplight-local.com:8080/api/v1/projects/chelsea/create-non-empty/nodes/reference/libs-params-common.v1.yaml#/components/parameters/Authorization'
        - schema:
          type: string
          enum:
            - '-name'
            - +name
            - '-dateOfBirth'
            - +dateOfBirth
            - dateOfBirth
            - name
          in: query
          name: sort
          description: Specify the parameter by which to sort. - Indicates the specified field descending where + indicates ascending.
        - $ref: 'http://chelsea.stoplight-local.com:8080/api/v1/projects/chelsea/create-non-empty/nodes/reference/libs-params-common.v1.yaml#/components/parameters/Content-Type'
        

components:
  schemas: {}
