openapi: 3.0.0
info:
  title: Test API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/test/{id}':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
    get:
      summary: Get A test
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../moosemodel.v1.json
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  hello:
                    type: string
                  test:
                    type: string
      operationId: get-test-id
  '/dog/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Get A Dog
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../moosemodel.v1.json
        '400':
          $ref: 'https://dojo-stg-v2.stoplight.io/api/v1/projects/chelsea/common-resources/nodes/common.oas3.yml#/components/responses/400'
components:
  schemas: {}
